# Generated by Django 3.0.6 on 2020-05-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycallboard', '0002_auto_20200518_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mycallboard.District', verbose_name='Район'),
        ),
    ]
