# Generated by Django 3.0.6 on 2020-05-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycallboard', '0004_auto_20200519_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
